// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in entgo.io/bug/ent/runtime.go

const (
	Version = "v0.10.2-0.20220614093246-195be2d98d88"           // Version of ent codegen.
	Sum     = "h1:0hl/c9ONVGutnFYcu6khrCt9wo6LJY4Qzb9mNMpAG/0=" // Sum of ent codegen.
)
