// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in entgo.io/bug/ent/runtime.go

const (
	Version = "v0.10.2-0.20220622152053-3bb5292c83bf"           // Version of ent codegen.
	Sum     = "h1:NB3e6L9oC1t8T62vchiJ9udVptF7BbEbXXy4FnJmYC0=" // Sum of ent codegen.
)
